### ISSUE TITLE
Move AccessToken library code for both libraries to new repository

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-accesstoken#1]
### Description

The code currently located at https://github.com/Altinn/altinn-studio/tree/master/src/Altinn.Common/Altinn.Common.AccessToken should be moved and reorganized here in this repo.

Folder structure:
./src/Altinn.AccessToken/** (csproj etc)
./src/Altinn.AccessTokenClient/** (csproj etc)
./Altinn.AccessToken.sln

Ensure that as much as possible of the commit history are kept for the files being moved.

### Additional Information

An tricky part of this job is to retain the commit history from the original repository for the files being transfered, but this job has been done before in for example the [Register](https://github.com/Altinn/altinn-register) repository.  

### Tasks

- [x] Move source code to new repository
    - Follow instructions here:  https://ao.ms/how-to-split-a-subdirectory-to-a-new-git-repository-and-keep-the-history/
    - Move code to root
    - Work on a branch that is not main in order to create a PR with the changes. 
    - Do NOT merge the PR, once approved, rather merge directly into main to keep commit history
- [x] Restructure repository
- [x] Set up new SonarCloud project
    - [x] Create new project
    - [x] Configure project
- [x] Move relevant pipelines to GitHub actions
    - [x] Disable Azure DevOps pipelines
    - [x] CodeQL (Replaces LGTM)
    - [x] Test & analysis for internal 
    - [x] Test & analysis for fork PR
    - [x] Delete Azure DevOps pipelines
- [x] Create build and publish workflows using GitHub actions.
    - Not doing this now. Moving to after we decide what to do with the versions of the two packages.
- [x] Add Renovate 
    - Renovate will add itself through a pull request. Just very slow repository discovery.
- [x] QA
- [x] Set up README.md for new repository
- [x] Delete source code from altinn-studio repository. Started: https://github.com/Altinn/altinn-studio/pull/9499
- [x] Delete outdated sonarcloud project

### Acceptance Criterias

- [x] Altinn.Common.AccessToken code is removed from the altinn-studio repository
- [x] Create a new branch in altinn-accestoken repo. Make a minor change. Create PR. Verify sonarcloud analysis is run. 
- [x] From a fork of altinn-accesstoken. Create a branch. Make a PR. Confirm that code coverage is available.

**Comment by SandGrainOne** [comment]
Completed all tasks.

**Comment by annerisbakk** [comment]
@SandGrainOne Endret status til Done
