### ISSUE TITLE
Upgrade Altinn.Common.AccessToken to dotnet v9

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-accesstoken#118]
.net9 has standard time support until May 12, 2026, but we should take the time to upgrade and not wait for .net 10. 

### Additional Information

[.NET Core Support lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
[Container Patching](https://pedia.altinn.cloud/altinn-3/ops/patching/containers/#net-core)

### Tasks

- [ ] ~~Update base images in the dockerfile for .net9~~
- [ ] Bump all projects; src and test, to .net9
- [ ] Update any build pipelines to support .net9
- [ ] Update any github workflows with .net9
- [ ] Check if we need to change anything in SonarCloud

### Acceptance Criterias

- [ ] Altinn.Common.AccessToken is built with .net9 tooling and run on .net9

**Comment by SandGrainOne** [comment]
In this case I want us to keep supporting .net8 as well. It already have support for both .net6 and .net8. Adding support for .net9 should be possible, but it might require some special handling of library differences. 

One of the things I know changed from .net 8 to .net9 was the loading of x509 certificates. I'm not sure what that would mean in term of package dependencies when building for all three versions of dotnet.
