### ISSUE TITLE
MinVerDefaultPreReleasePhase is deprecated, replace with MinVerDefaultPreReleaseIdentifiers

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-accesstoken#57]
### Description

There is currently a build warning about MinVerDefaultPreReleasePhase being deprecated. Follow the documentation of what do to instead and perform some testing.

```[tasklist]
### Tasks
- [ ] Find correct way of setting prerelease for us. Use recommended settings if that is working for us.
- [ ] Test generate stable and prerelease packages
```

```[tasklist]
### Acceptance Criteria
- [ ] It's possible to generate a prerelease version by setting a tag 
- [ ] It's possible to generate a stable version by setting a tag 
```

**Comment by SandGrainOne** [comment]
This was fixed in #74
